
module.exports.products =  [
    {
        "id": 1,
        "title": "iPhone 9",
        "description": "An apple mobile which is nothing like apple",
        "price": 549,
        "brand": "apple",
        "operating":"apple",
        "ram":"6gb",
        "processor":"apple",
        "thumbnail":"https://st1.techlusive.in/wp-content/uploads/2022/02/picturesapple-iphone-9-mobile-phone-large-3.jpg?impolicy=Medium_Widthonly&w=220"
    },
    {
        "id": 2,
        "title": "iPhone X",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "brand": "apple",
        "operating":"apple",
        "ram":"8gb",
        "processor":"apple",
        "thumbnail":"https://www.refurbkart.com/cdn/shop/products/iphonexwhite.png?v=1671625120"
    },
    {
        "id": 3,
        "title": "Samsung Universe 9",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "brand": "samsung",
        "operating":"android",
        "ram":"12gb",
        "processor":"exynos",
        "thumbnail":"https://files.ekmcdn.com/hdewcameras/images/open-box-samsung-galaxy-note-9-dual-sim-n960fd-128gb-black-11138-p.jpg"
    },
    {
        "id": 4,
        "title": "Vivo V9",
        "description": "Vivo V9 is officially announced on April 2021.",
        "price": 280,
        "brand": "vivo",
        "operating":"android",
        "ram":"8gb",
        "processor":"mediatek",
        "thumbnail":"https://cdn11.bigcommerce.com/s-o9pppsyjzh/images/stencil/1280x1280/products/404561/12126321/V1212400__1__78228.1689911843.jpg?c=1"
    },
    {
        "id": 5,
        "title": "Oneplus 11",
        "description": "Oneplus re-badged 11 New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "brand": "oneplus",
        "operating":"android",
        "ram":"12gb",
        "processor":"snapdrgaon",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61amb0CfMGL._AC_UF894,1000_QL80_.jpg"
    },
    {
        "id": 6,
        "title": "Google Pixel 7",
        "description": "An google mobile which is nothing like google",
        "price": 549,
        "brand": "google",
        "operating":"google",
        "ram":"8gb",
        "processor":"google",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51OFxuD1GgL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        "id": 7,
        "title": "Redmi Note 10",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "brand": "redmi",
        "operating":"android",
        "ram":"6gb",
        "processor":"snapdrgaon",
        "thumbnail":"https://cdn1.smartprix.com/rx-idwRaGM0X-w1200-h1200/dwRaGM0X.jpg"
    },
    {
        "id": 8,
        "title": "Samsung Note 20",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "brand": "samsung",
        "operating":"android",
        "ram":"12gb",
        "processor":"snapdrgaon",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61XRjDpHtXS._AC_UF1000,1000_QL80_.jpg"
    },
    {
        "id": 9,
        "title": "Oneplus 8t",
        "description": "New oneplus with exciting features",
        "price": 280,
        "brand": "oneplus",
        "operating":"android",
        "ram":"6gb",
        "processor":"mediatek",
        "thumbnail":"https://www.neolight.in/wp-content/uploads/2022/01/oneplus-8t-green.jpg"
    },
    {
        "id": 10,
        "title": "Motorola",
        "description": "Motorola re-badged 11 New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "brand": "moto",
        "operating":"android",
        "ram":"6gb",
        "processor":"snapdrgaon",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71AnGkTZ9xL._AC_UF894,1000_QL80_.jpg"
    },
    {
        "id": 11,
        "title": "Google Pixel 6",
        "description": "An Google mobile which is nothing like Google",
        "price": 549,
        "brand": "google",
        "operating":"google",
        "ram":"4gb",
        "processor":"google",
        "thumbnail":"https://5.imimg.com/data5/SELLER/Default/2023/3/292019941/UI/OA/SN/104903331/google-pixel-6-pro-mobile-phone.jpg"
    },
    {
        "id": 12,
        "title": "Vivo v11",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "brand": "vivo",
        "operating":"android",
        "ram":"12gb",
        "processor":"snapdragon",
        "thumbnail":"https://cdn11.bigcommerce.com/s-o9pppsyjzh/images/stencil/1280x1280/products/404561/12126321/V1212400__1__78228.1689911843.jpg?c=1"
    },
    {
        "id": 13,
        "title": "iPhone 14",
        "description": "Apple's new variant which goes beyond iPhone to the Universe",
        "price": 1249,
        "brand": "apple",
        "operating":"apple",
        "ram":"8gb",
        "processor":"apple",
        "thumbnail":"https://www.apple.com/newsroom/images/product/iphone/standard/Apple-iPhone-14-iPhone-14-Plus-2up-purple-220907_inline.jpg.large.jpg"
    },
    {
        "id": 14,
        "title": "Asus Phone 10",
        "description": "Asus is officially announced on April 2021.",
        "price": 280,
        "brand": "asus",
        "operating":"android",
        "ram":"12gb",
        "processor":"snapdragon",
        "thumbnail":"https://cdn1.smartprix.com/rx-i62sQIRiK-w420-h420/asus-zenfone-10.jpg"
    },
    {
        "id": 15,
        "title": "Oneplus 10r",
        "description": "Oneplus re-badged 11 New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "brand": "oneplus",
        "operating":"android",
        "ram":"8gb",
        "processor":"mediatek",
        "thumbnail":"https://s3b.cashify.in/gpro/uploads/2022/09/24155502/oneplus-10r-prime-blue-edition-extra.jpg"
    },
    {
        "id": 16,
        "title": "Google Pixel 8",
        "description": "An Google mobile which is nothing like Google",
        "price": 549,
        "brand": "google",
        "operating":"google",
        "ram":"12gb",
        "processor":"google",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/713eEl39eLL._AC_UF894,1000_QL80_.jpg"
    },
    {
        "id": 17,
        "title": "Oppo Reno",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "brand": "oppo",
        "operating":"android",
        "ram":"6gb",
        "processor":"mediatek",
        "thumbnail":"https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/3/u/w/-original-imagtcrvzrqnnxpc.jpeg?q=20"
    },
    {
        "id": 18,
        "title": "Samsung Galaxy 11",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "brand": "samsung",
        "operating":"android",
        "ram":"8gb",
        "processor":"exynos",
        "thumbnail":"https://www.smartcellular.in/media/catalog/product/cache/cfaa1692031f009488d1cfea5ce7e1ee/5/1/51aqup4tyyl._ac_sl1000__1.jpg"
    },
    {
        "id": 19,
        "title": "Vivo v5",
        "description": "Vivo V5 is officially announced on April 2021.",
        "price": 280,
        "brand": "vivo",
        "operating":"android",
        "ram":"6gb",
        "processor":"mediatek",
        "thumbnail":"https://www.gizmochina.com/wp-content/uploads/2017/09/Vivo-V5-Plus-Profile-Page-550x550.jpg"
    },
    {
        "id": 20,
        "title": "Oneplus 10t",
        "description": "Oneplus re-badged 11 New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "brand": "oneplus",
        "operating":"android",
        "ram":"8gb",
        "processor":"snapdrgaon",
        "thumbnail":"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71XKAnxCsLL._AC_UF894,1000_QL80_.jpg"
    },
];